import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div style={{ width: '100vw', height: '100vh', background: 'gray' }}>
          <div style={{ width: '100%', height: '30px', background: 'red' }}>Header</div>
          {children}
        </div>
      </body>
    </html>
  );
}
